# stage1 as builder
FROM node:12-alpine

RUN apk update && apk upgrade && \
  apk add --no-cache bash git openssh

WORKDIR /casty-dash

# Copy the package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy rest of the files
COPY . .